name: jtech_pomelo
description: A jtech flutter base lib
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # 加密算法库(ANDROID/IOS/LINUX/MACOS/WEB/WINDOWS)
  crypto: ^3.0.2

  # 日志(ANDROID/IOS/LINUX/MACOS/WEB/WINDOWS)
  logger: ^1.1.0

  # 数据存储管理(ANDROID/IOS/LINUX/MACOS/WEB/WINDOWS)
  shared_preferences: ^2.0.15

  # 网络请求框架(ANDROID/IOS/LINUX/MACOS/WEB/WINDOWS)
  dio: ^4.0.6

  # 附件选择(ANDROID/IOS/LINUX/MACOS/WEB/WINDOWS)
  file_picker: ^4.5.1

  # 表格分割组件(ANDROID/IOS/LINUX/MACOS/WEB/WINDOWS)
  flutter_staggered_grid_view: ^0.6.1

  # 刷新组件(ANDROID/IOS/LINUX/MACOS/WEB/WINDOWS)
  pull_to_refresh: ^2.0.0

  # 索引列表组件(ANDROID/IOS/LINUX/MACOS/WEB/WINDOWS)
  azlistview: ^2.0.0

  # 拼音库(ANDROID/IOS/LINUX/MACOS/WEB/WINDOWS)
  lpinyin: ^2.0.3

  # 字体/图标库(ANDROID/IOS/LINUX/MACOS/WEB/WINDOWS)
  font_awesome_flutter: ^10.1.0

  # 功能执行(ANDROID/IOS/LINUX/MACOS/WEB/WINDOWS)
  url_launcher: ^6.1.2

  # 包信息(ANDROID/IOS/LINUX/MACOS/WEB/WINDOWS)
  package_info_plus: ^1.4.2

  # 图片扩展(ANDROID/IOS/LINUX/MACOS/WEB/WINDOWS)
  extended_image: ^6.1.0

  # 路径管理(ANDROID/IOS/LINUX/MACOS/WINDOWS)
  path_provider: ^2.0.10

  # 本地通知栏管理(ANDROID/IOS/LINUX/MACOS)
  flutter_local_notifications: ^9.5.2

  # 权限管理(ANDROID/IOS/WINDOWS)
  permission_handler: ^9.2.0

  # 消息提示管理(ANDROID/IOS/WEB)
  fluttertoast: ^8.0.9

  # 图片视频选择(ANDROID/IOS/WEB)
  image_picker: ^0.8.5+2

  # 视频播放器(对video_player的封装)(ANDROID/IOS/WEB)
  chewie: ^1.3.2

  # 视频播放器(ANDROID/IOS/WEB)
  video_player: ^2.4.2

  # 图片编辑(ANDROID/IOS)
  image_editor: ^1.0.2

  # 图片压缩(ANDROID/IOS)
  flutter_image_compress: ^1.1.0

  # android ota更新(ANDROID)
  flutter_xupdate: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages